name       : util-linux
version    : '2.28'
release    : 17
source     :
    - https://www.kernel.org/pub/linux/utils/util-linux/v2.28/util-linux-2.28.tar.xz : 395847e2a18a2c317170f238892751e73a57104565344f8644090c8b091014bb
homepage   : http://freecode.com/projects/util-linux
license    :
    - GPL-2.0
    - LPL-2.1
    - BSD-3-Clause
summary    : util-linux (Essential Linux utilties)
component  : system.base
emul32     : yes
description: |
    Util-linux is a suite of essential tools for any Linux system, such as chsh, kill, cfdisk, mkfs, mount, and more.
autodep    : no
devel      : yes
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --prefix=/usr \
                --disable-static \
                --enable-libmount-force-mountinfo
    else
        %configure --disable-login \
                   --disable-nologin \
                   --disable-chfn-chsh \
                   --disable-su \
                   --disable-static
    fi
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib{uuid,blkid,fdisk,mount,smartcols}.la
    else
        %make
    fi
install    : "if [[ ! -z \"${EMUL32BUILD}\" ]]; then\n    %make install-usrlib_execLTLIBRARIES install-pkgconfigDATA DESTDIR=\"$installdir\"\nelse\n    %make_install\n    \n    rm -v $installdir/usr/share/man/man8/fsck.8\n\
    \    ln -sv /bin/mount $installdir/usr/bin/mount\n    ln -sv /bin/umount $installdir/usr/bin/umount\n    install -m 00755 $pkgfiles/arch $installdir/bin/arch\n    rm -v $installdir/usr/share/bash-completion/completions/{mount,umount}\n\
    fi\n"
