name       : util-linux
version    : 2.39.1
release    : 38
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-2.39.1.tar.xz : 890ae8ff810247bd19e274df76e8371d202cda01ad277681b0ea88eeaa00286b
license    :
    - BSD-3-Clause
    - BSD-4-Clause-UC
    - GPL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - Public-Domain
component  : system.base
summary    : util-linux (Essential Linux utilties)
description: |
    Util-linux is a suite of essential tools for any Linux system, such as chsh, kill, cfdisk, mkfs, mount, and more.
emul32     : yes
autodep    : no
devel      : yes
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(libeconf)
    - pkgconfig32(zlib)
    # These are only needed for tests
    - pkgconfig32(ncursesw)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
    - pkgconfig32(libxcrypt)
    - libgcrypt-32bit-devel
    - pam-32bit-devel
setup      : |
    # Fix usage with musl
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-pylibmount \
                   --prefix=/usr
    else
        %configure --disable-chfn-chsh \
                   --disable-login \
                   --disable-nologin \
                   --disable-su \
                   --with-vendordir=/usr/share/defaults/etc
    fi
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib{uuid,blkid,fdisk,mount,smartcols}.la
    else
        %make
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make install-usrlib_execLTLIBRARIES install-pkgconfigDATA DESTDIR="$installdir"
    else
        %make_install

        rm -v $installdir/usr/share/man/man8/fsck.8
        install -m 00755 $pkgfiles/arch $installdir/usr/bin/arch
        rm -v $installdir/usr/share/bash-completion/completions/{mount,umount,rfkill}

        install -Dm00644 $pkgfiles/runuser $installdir/usr/share/defaults/etc/pam.d/runuser
        install -Dm00644 $pkgfiles/runuser-l $installdir/usr/share/defaults/etc/pam.d/runuser-l

        # Install compat links T10615
        for TOP in {bin,sbin}; do
            install -D -d -m 00755 $installdir/$TOP
            pushd $installdir/usr/$TOP
            for FILE in *; do
                ln -sv /usr/$TOP/$FILE $installdir/$TOP/$FILE
            done
            popd
        done
    fi
# Tests compile but they are not run because of
# "Ignore util-linux test suite [non-root UID expected]."
#check      : |
#    %make check
