name       : util-linux
version    : 2.33.1
release    : 24
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.33/util-linux-2.33.1.tar.xz : c14bd9f3b6e1792b90db87696e87ec643f9d63efa0a424f092a5a6b2f2dbef21
homepage   : https://freecode.com/projects/util-linux
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-or-later
    - Public-Domain
component  : system.base
summary    : util-linux (Essential Linux utilties)
description: |
    Util-linux is a suite of essential tools for any Linux system, such as chsh, kill, cfdisk, mkfs, mount, and more.
emul32     : yes
autodep    : no
devel      : yes
builddeps  :
    - pkgconfig32(zlib)
setup      : |
    # Fix usage with musl
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --prefix=/usr \
                --enable-libmount-support-mtab
    else
        %configure --disable-login \
                   --disable-nologin \
                   --disable-chfn-chsh \
                   --disable-su \
                   --enable-libmount-support-mtab
    fi
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib{uuid,blkid,fdisk,mount,smartcols}.la
    else
        %make
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make install-usrlib_execLTLIBRARIES install-pkgconfigDATA DESTDIR="$installdir"
    else
        %make_install

        rm -v $installdir/usr/share/man/man8/fsck.8
        ln -sv /bin/mount $installdir/usr/bin/mount
        ln -sv /bin/umount $installdir/usr/bin/umount
        install -m 00755 $pkgfiles/arch $installdir/bin/arch
        rm -v $installdir/usr/share/bash-completion/completions/{mount,umount,rfkill}
    fi
