name        : util-linux
version     : 2.26
release     : 7
source      :
    - https://www.kernel.org/pub/linux/utils/util-linux/v2.26/util-linux-2.26.tar.xz : a23c6f39dea0ed215ccd589509ffc7bb6f706f6e1a04760f493fb0fd7e93c489
homepage    : http://freecode.com/projects/util-linux
license     :
    - GPL-2.0
    - LPL-2.1
    - BSD-3-Clause
summary     : util-linux (Essential Linux utilties)
description : |
    Util-linux is a suite of essential tools for any Linux system, such as chsh, kill, cfdisk, mkfs, mount, and more.
autodep    : no
devel      : yes
setup      : |
    %configure --disable-login \
               --disable-nologin \
               --disable-chfn-chsh \
               --disable-su \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    
    rm -v $installdir/usr/share/man/man8/fsck.8
    ln -sv /bin/mount $installdir/usr/bin/mount
    ln -sv /bin/umount $installdir/usr/bin/umount
