name       : util-linux
version    : 2.37.4
release    : 29
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.37/util-linux-2.37.4.tar.xz : 634e6916ad913366c3536b6468e7844769549b99a7b2bf80314de78ab5655b83
license    :
    - BSD-3-Clause
    - BSD-4-Clause-UC
    - GPL-2.0-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - Public-Domain
component  : system.base
summary    : util-linux (Essential Linux utilties)
description: |
    Util-linux is a suite of essential tools for any Linux system, such as chsh, kill, cfdisk, mkfs, mount, and more.
emul32     : yes
autodep    : no
devel      : yes
builddeps  :
    - pkgconfig32(zlib)
    # These are only needed for tests
    - pkgconfig32(ncursesw)
    - pkgconfig32(liblzma)
    - pkgconfig32(libsystemd)
    - libgcrypt-32bit-devel
    - pam-32bit-devel
setup      : |
    %patch -p1 < $pkgfiles/findmnt-output-all-fix.patch
    # Fix usage with musl
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-pylibmount \
                   --enable-libmount-support-mtab \
                   --prefix=/usr
    else
        %configure --disable-chfn-chsh \
                   --disable-login \
                   --disable-nologin \
                   --disable-su \
                   --enable-libmount-support-mtab
    fi
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make lib{uuid,blkid,fdisk,mount,smartcols}.la
    else
        %make
    fi
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %make install-usrlib_execLTLIBRARIES install-pkgconfigDATA DESTDIR="$installdir"
    else
        %make_install

        rm -v $installdir/usr/share/man/man8/fsck.8
        ln -sv /bin/mount $installdir/usr/bin/mount
        ln -sv /bin/umount $installdir/usr/bin/umount
        install -m 00755 $pkgfiles/arch $installdir/bin/arch
        rm -v $installdir/usr/share/bash-completion/completions/{mount,umount,rfkill}
    fi
# Tests compile but they are not run because of
# "Ignore util-linux test suite [non-root UID expected]."
#check      : |
#    %make check
